# Generated by Django 4.1.3 on 2022-12-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cdr',
            field=models.ImageField(default=1, upload_to='CDRFiles/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(upload_to='images'),
        ),
    ]
